version: '3'

services:
  backend-test:
    container_name: backend_test
    build:
      context: ./Go
      dockerfile: srv/Dockerfile.test
    volumes:
      - api_test:/usr/src/app/
    depends_on:
      live-postgres:
        condition: service_healthy
    networks:
      - backend_test

  live-postgres:
    image: postgres:latest
    container_name: test_db_postgress
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sport_events
      - DATABASE_HOST=live-postgres
    ports:
      - "5432:5432"
    volumes:
      - database_postgres_test:/var/lib/postgresql/data
    networks:
      - backend_test
    healthcheck:
      test: "exit 0"

volumes:
  api_test:
  database_postgres_test:

# Networks to be created to facilitate communication between containers
networks:
  backend_test:
    driver: bridge
